#!/bin/bash
rsync -av --progress --delete /etc/passwd /backup
rsync -av --progress --delete /etc/shadow /backup
rsync -av --progress --delete /etc/group /backup
rsync -av --progress --delete /etc/gshadow /backup
rsync -av --progress --delete /etc/hosts /backup
rsync -av --progress --delete /etc/ansible /backup
rsync -av --progress --delete /home/ansible/.ssh /backup
rsync -av --progress --delete /home /backup
rsync -av --progress --delete /root /backup

